# ============================================================
# RELLIS-3D Raw Semantic Label Mapping
# ============================================================

labels:
  0: void
  1: dirt
  3: grass
  4: tree
  5: pole
  6: water
  7: sky
  8: vehicle
  9: object
  10: asphalt
  12: building
  15: log
  17: person
  18: fence
  19: bush
  23: concrete
  27: barrier
  31: puddle
  33: mud
  34: rubble
